development:
  adapter: postgresql
  encoding: unicode
  database: myinventory_development
  pool: 5
  username: WillReilly
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: myinventory_test
  pool: 5
  username: WillReilly
  password:
